// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPShop.Models;

namespace RPShop.Migrations
{
    [DbContext(typeof(RPDbcontext))]
    partial class RPDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RPShop.Models.Entities.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("totalPrice")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RPShop.Models.Entities.Inventory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<double>("importPrice")
                        .HasColumnType("float");

                    b.Property<int>("productid")
                        .HasColumnType("int");

                    b.Property<int>("supplierid")
                        .HasColumnType("int");

                    b.Property<double>("total")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("productid");

                    b.ToTable("Inventorys");
                });

            modelBuilder.Entity("RPShop.Models.Entities.Oder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OderDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("customerid")
                        .HasColumnType("int");

                    b.Property<int>("cutomer_id")
                        .HasColumnType("int");

                    b.Property<int>("employeeid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("customerid");

                    b.ToTable("Oders");
                });

            modelBuilder.Entity("RPShop.Models.Entities.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Customerid")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("supplierid")
                        .HasColumnType("int");

                    b.Property<int>("typeProductid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Customerid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RPShop.Models.Entities.Inventory", b =>
                {
                    b.HasOne("RPShop.Models.Entities.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RPShop.Models.Entities.Oder", b =>
                {
                    b.HasOne("RPShop.Models.Entities.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerid");
                });

            modelBuilder.Entity("RPShop.Models.Entities.Product", b =>
                {
                    b.HasOne("RPShop.Models.Entities.Customer", null)
                        .WithMany("Products")
                        .HasForeignKey("Customerid");
                });
#pragma warning restore 612, 618
        }
    }
}
